name: ML

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: update
      run: sudo apt-get -y update
    - name: upgrade
      run: sudo apt-get -y upgrade
    - name: unzip
      run: sudo apt-get install -y unzip 
    - name: build-essential
      run: sudo apt-get install -y build-essential
    - name: gdb
      run: sudo apt-get install -y gdb
    - name: git
      run: sudo apt-get install -y git
    - name: cmake
      run: sudo apt-get install -y cmake
    - name: cmake-curses-gui
      run: sudo apt-get install -y cmake-curses-gui
    - name: python
      run: sudo apt-get install -y python
    - name: libblas-dev
      run: sudo apt-get install -y libblas-dev
    - name: libopenblas-dev
      run: sudo apt-get install -y libopenblas-dev
    - name: libatlas-base-dev
      run: sudo apt-get install -y libatlas-base-dev
    - name: liblapack-dev
      run: sudo apt-get install -y liblapack-dev
    - name: libboost-all-dev
      run: sudo apt-get install -y libboost-all-dev
    - name: libopencv-dev
      run: sudo apt-get install -y libopencv-dev
    - name: python3-opencv
      run: sudo apt-get install -y python3-opencv
    - name: libopencv-dev
      run: sudo apt-get install -q -y libopencv-dev
    - name: libopencv-highgui-dev
      run: sudo apt-get install -y libopencv-highgui-dev
    - name: libhdf5-dev
      run: sudo apt-get install -y libhdf5-dev
    - name: libjson-c-dev
      run: sudo apt-get install -y libjson-c-dev
    - name: libx11-dev
      run: sudo apt-get install -y libx11-dev
    - name: openjdk-8-jdk
      run: sudo apt-get install -y openjdk-8-jdk
    - name: wget
      run: sudo apt-get install -y wget
    - name: ninja-build
      run: sudo apt-get install -y ninja-build
    - name: gnuplot
      run: sudo apt-get install -y gnuplot
    - name: vim
      run: sudo apt-get install -y vim
    - name: python3-venv
      run: sudo apt-get install -y python3-venv
    - name: libeigen3-dev
      run: sudo apt-get install -y libeigen3-dev
    - name: libmlpack-dev
      run: sudo apt-get install -y libmlpack-dev
    - name: mlpack-bin
      run: sudo apt-get install -y mlpack-bin
    - name: libarmadillo-dev
      run: sudo apt-get install -y libarmadillo-dev
    - name: libblas-dev
      run: sudo apt-get install -y libblas-dev
    - name: libensmallen-dev
      run: sudo apt-get install -y libensmallen-dev
    - name: pyyaml
      run: pip install pyyaml
    - name: typing
      run: pip install typing
