name: ML

on:
  push:
    branches: [ main ]
  pull_requests:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: build-essential
      run: apt-get install -y build-essential

