name: ML

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: build-essential
      run: sudo apt-get install -y build-essential
    - name: gdb
      run: sudo apt-get install -y gdb
    - name: git
      run: sudo apt-get install -y git
    - name: cmake
      run: sudo apt-get install -y cmake
    - name: cmake-curses-gui
      run: sudo apt-get install -y cmake-curses-gui
    - name: python
      run: sudo apt-get install -y python
    - name: libblas-dev
      run: sudo apt-get install -y libblas-dev
    - name: libopenblas-dev
      run: sudo apt-get install -y libopenblas-dev
    - name: libatlas-base-dev
      run: sudo apt-get install -y libatlas-base-dev
    - name: liblapack-dev
      run: sudo apt-get install -y liblapack-dev
    - name: libboost-all-dev
      run: sudo apt-get install -y libbboost-all-dev
    - name: libopencv-core3.2
      run: sudo apt-get install -y libopencv-core3.2
    - name: libopencv-imgproc3.2
      run: sudo apt-get install -y libopencv-imgproc3.2
    - name: libopencv-dev
      run: sudo apt-get install -q -y libopencv-dev
    - name: libopencv-highgui3.2
      run: sudo apt-get install -y libopencv-highgui3.2
    - name: libopencv-highgui-dev
      run: sudo apt-get install -y libopencv-highgui-dev
    - name: libhdf5-dev
      run: sudo apt-get install -y libhdf5-dev
    - name: libjson-c-dev
      run: sudo apt-get install -y libjson-c-dev
    - name: libx11-dev
      run: sudo apt-get install -y libx11-dev
    - name: openjdf-8-jdk
      run: sudo apt-get install -y openjdf-8-jdk
    - name: wget
      run: sudo apt-get install -y wget
    - name: ninja-build
      run: sudo apt-get install -y ninja-build
    - name: gnuplot
      run: sudo apt-get install -y gnuplot
    - name: vim
      run: sudo apt-get install -y vim
    - name: python3-venv
      run: sudo apt-get install -y python3-venv
    - name: pyyaml
      run: pip install pyyaml
    - name: typing
      run: pip install typing
